home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from home import views


app_name = "home"


urlpatterns = [
    path('about/', views.About.as_view(), name="about"),
    path('', auth_views.LoginView.as_view(template_name="home/index.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="home/index.html"), name="logout"),
    path('signup/', views.Signup.as_view(), name="signup"),
    path('wsexample/', views.WSexample, name="wsexample"),
    path('wsClients/', views.wsClientAPI, name="wsclients"),
]

vsubs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]

home/models.py
from django.db import models

# Create your models here.

class Client(models.Model):
    name = models.CharField(max_length=32)
    city = models.CharField(max_length=32)
    

memberships/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
import stripe
# Create your models here.


"""
Memberships
- slug
- membership_type(Free, Professional, Enterprise)
- price
- stripe_plan_id
"""

stripe.api_key = settings.STRIPE_SECRET_KEY


MEMBERSHIP_CHOICES = (
    ("Free", "Free"),
    ("Professional", "Pro"),
)


class Membership(models.Model):
    slug = models.SlugField()
    membership_type = models.CharField(max_length=32, choices=MEMBERSHIP_CHOICES)
    price = models.IntegerField()
    stripe_plan_id = models.CharField(max_length=32)
    
    
    def __str__(self):
        return self.membership_type
    

"""
UserMemberships
- user(ForeignKey to Users)
- stripe_costumer_id
- membership_type(ForeignKey to Memberships)
"""

class UserMembership(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    stripe_costumer_id = models.CharField(max_length=32)
    membership_type = models.ForeignKey(Membership, on_delete=models.CASCADE, null=True)
    
    
    def __str__(self):
        return self.user.username


def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
    if created:
        UserMembership.objects.get_or_create(user=instance)
    user_membership, created = UserMembership.objects.get_or_create(user=instance)
    
    if user_membership.stripe_costumer_id is None or user_membership.stripe_costumer_id=="":
        new_costumer_id = stripe.Customer.create( description=instance.username, email=instance.email)
        user_membership.stripe_costumer_id = new_costumer_id["id"]
        user_membership.save()

post_save.connect(post_save_usermembership_create, sender=settings.AUTH_USER_MODEL)

"""
Subscriptions
- user_membership(ForeignKey to UserMemberships)
- stripe_subscription_id
- active 
"""

class Subscription(models.Model):
    user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
    stripe_subscription_id = models.CharField(max_length=32, blank=True, null=True)
    active = models.BooleanField(default=True)
    
    def __str__(self) -> str:
        return self.user_membership.user.username

home/forms.py
from django import forms
from django.contrib.auth.models import User

class SignupForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "password", "email"]
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'})
        }

home/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.core import serializers
from django.http import HttpResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status


from .forms import SignupForm
from .models import Client
from .serializers import ClientSerializer
# Create your views here.


class About(generic.TemplateView):
    template_name = "home/about.html"


class Signup(generic.CreateView):
    template_name = "home/signup.html"
    model = User
    form_class = SignupForm
    success_url = reverse_lazy("home:login")



def WSexample(request):
    data = serializers.serialize("json", Client.objects.all())
    return HttpResponse(data, content_type="application/json")


##### C R U D #####

## RETRIEVE or READ ##
# LIST(GET) # CREATE(POST)
@api_view(["GET", "POST"])
def wsClientAPI(request):
    if request.method=="GET":
        data = ClientSerializer(Client.objects.all(), many=True)
        return Response(data=data.data, status=status.HTTP_200_OK)
    elif request.method=="POST":
        data = ClientSerializer(data=request.data)
        if data.is_valid():
            data.save()
            return Response(data.data, status=status.HTTP_201_CREATED)
        return Response(data.errors, status=status.HTTP_400_BAD_REQUEST)

memberships/views.py
from django.shortcuts import render

# Create your views here.

templates/home/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h2>About Template</h2>
</body>
</html>

templates/home/index.html
{% if request.user.is_authenticated %}

    <h2>Bienvenido User: {{ request.user }} </h2>
    <h3><a href="{% url 'home:logout' %}">LogOut</a></h3>

{% else %}
<body class="h-100">
    <div class="authincation h-100">
        <div class="container-fluid h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
                                    <h4 class="text-center mb-4">Sign in your account</h4>
                                    <form method="post">
                                        {% csrf_token %}
                                        
                                        <button type="submit" class="btn btn-outline-primary">Login</button>	

                                        {{ form.as_p }} 
                                    
                                        <div class="form-group">
                                            <label><strong>Email</strong></label>
                                            <input type="text" class="form-control"  >
                                        </div>
                                        <div class="form-group">
                                            <label><strong>Password</strong></label>
                                            

                                            <input type="password" class="form-control" >
                                        </div>
                                        <div class="form-row d-flex justify-content-between mt-4 mb-2">
                                            <div class="form-group">
                                                <div class="form-check ml-2">
                                                    <input class="form-check-input" type="checkbox" id="basic_checkbox_1">
                                                    <label class="form-check-label" for="basic_checkbox_1">Remember me</label>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <a href="page-forgot-password.html">Forgot Password?</a>
                                            </div>
                                        </div>
                                        <div class="text-center">
                                            <button type="submit" class="btn btn-primary btn-block">Sign me in</button>
                                        </div>
                                    </form>
                                    <div class="new-account mt-3">
                                        <p>Don't have an account? <a class="text-primary" href="{% url 'home:signup' %}">Sign up</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

templates/home/signup.html
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
    </div>
    <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
    </div>
    <div class="form-group">
        <label for="password_confirm">Confirm Password</label>
        <input type="password" class="form-control" id="password_confirm" name="password_confirm" placeholder="Confirm Password">
    </div>

    <div class="text-center">
        <button type="submit" class="btn btn-primary btn-block">Done</button>
    </div>
</form>

templates/home/wsexample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WSEXAMPLE</title>
</head>
<body>
    <h2>Hola User: {{request.user}}, este es el API de ejemplo.</h2>
</body>
</html>